apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: lgtm
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`grafana.local`)
      services:
        - name: grafana
          port: 80
  tls:
    certResolver: default
