apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: mimir-distributed
    targetRevision: '5.5.0'
    helm:
      values: |
        mimir:
          structuredConfig:
            common:
              storage:
                backend: filesystem
            blocks_storage:
              backend: filesystem
              filesystem:
                dir: /data/mimir-blocks
        minio:
          enabled: false
        nginx:
          replicas: 1
        distributor:
          replicas: 1
        ingester:
          replicas: 1
          persistentVolume:
            enabled: true
            size: 10Gi
        querier:
          replicas: 1
        query_frontend:
          replicas: 1
        store_gateway:
          replicas: 1
          persistentVolume:
            enabled: true
            size: 10Gi
        compactor:
          replicas: 1
          persistentVolume:
            enabled: true
            size: 10Gi
        ruler:
          replicas: 0
        alertmanager:
          replicas: 0
  destination:
    namespace: lgtm
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
