apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm-distributed
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: lgtm-distributed
    targetRevision: '3.0.1'
    helm:
      values: |
        grafana:
          enabled: true
        loki:
          enabled: true
        mimir:
          enabled: true
        tempo:
          enabled: true
        grafana-oncall:
          enabled: false
  destination:
    namespace: lgtm
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      