apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: '1.10.5'
    helm:
      values: |
        tempo:
          storage:
            trace:
              backend: local
              local:
                path: /var/tempo/traces
          metricsGenerator:
            enabled: true
            remoteWriteUrl: http://mimir-nginx.lgtm.svc:80/api/v1/push
        persistence:
          enabled: true
          size: 10Gi
        replicas: 1
  destination:
    namespace: lgtm
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
